version: '3'
services:
  mssql:
    image: mcr.microsoft.com/mssql/server:2017-latest
    container_name: dist-tracing-mssql
    command: /bin/bash ./entrypoint.sh
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_PID=Express
      - SA_PASSWORD=Aa123456Qw!@
    volumes:
      - mssqldata:/var/opt/mssql/data
      - ./mssql-entrypoint.sh:/entrypoint.sh
      - ./mssql-configure-db.sh:/configure-db.sh
      - ./mssql-setup.sql:/setup.sql
    ports:
      - 1433:1433
    networks:
      - dist-tracing
  redis:
    image: redis:alpine
    container_name: dist-tracing-redis
    ports:
      - 6379:6379
    networks:
      - dist-tracing
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.10.2
    container_name: dist-tracing-elasticsearch
    environment:
      - node.name=elasticsearch
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - elasticsearchdata:/usr/share/elasticsearch/data       
    ports:
      - 9200:9200
    networks:
      - dist-tracing
  kibana:
    image: docker.elastic.co/kibana/kibana:7.10.2
    container_name: dist-tracing-kibana
    ports:
      - 5601:5601
    environment:
      ELASTICSEARCH_URL: http://elasticsearch:9200
      ELASTICSEARCH_HOSTS: http://elasticsearch:9200
      XPACK_ENCRYPTEDSAVEDOBJECTS_ENCRYPTIONKEY: "EePXCifCaykPORwjqKGbINHCPFYnNXZT"
    networks:
      - dist-tracing
  apm:
    image: docker.elastic.co/apm/apm-server:7.10.2
    container_name: dist-tracing-apm
    cap_add: ["CHOWN", "DAC_OVERRIDE", "SETGID", "SETUID"]
    cap_drop: ["ALL"]
    ports:
    - 8200:8200
    networks:
    - dist-tracing
    command: >
       apm-server -e
         -E apm-server.rum.enabled=true
         -E setup.kibana.host=kibana:5601
         -E setup.template.settings.index.number_of_replicas=0
         -E apm-server.kibana.enabled=true
         -E apm-server.kibana.host=kibana:5601
         -E output.elasticsearch.hosts=["elasticsearch:9200"]
    depends_on:
      - kibana
      - elasticsearch
  opentelemetry-collector:
    container_name: dist-tracing-opentelemetry-collector
    image: otel/opentelemetry-collector-contrib:latest
    command: ["--config=/etc/otel-collector-config.yaml","--log-level=DEBUG"]
    volumes:
      - ./opentelemetry-collector-config.yaml:/etc/otel-collector-config.yaml
    ports:
      - "1888:1888"   # pprof extension
      - "8888:8888"   # Prometheus metrics exposed by the collector
      - "8889:8889"   # Prometheus exporter metrics
      - "13133:13133" # health_check extension
      - "55680:55680" # OTLP gRPC receiver
      - "55670:55679" # zpages extension
    depends_on:
      - apm
    networks:
      - dist-tracing
      
volumes:
  mssqldata:
    driver: local
  elasticsearchdata:
    driver: local

networks:
  dist-tracing:
    driver: bridge